name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Copy files
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_ADDRESS: ${{ secrets.DEPLOY_ADDRESS }}
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p "$DEPLOY_PORT" -H "$DEPLOY_ADDRESS" >> ~/.ssh/known_hosts
        rsync -avz --delete -e "ssh -i ~/.ssh/id_ed25519 -p $DEPLOY_PORT" ./ $DEPLOY_USER@$DEPLOY_ADDRESS:/var/www/html/
